# Placeholder models - will be generated by openapi-python-client
from typing import Union, List, Optional, Dict, Any
from datetime import date, datetime

class IRSSpec:
    """Interest Rate Swap specification"""
    pass

class CCSSpec:
    """Cross Currency Swap specification"""
    pass

class RunRequest:
    """Request to run a valuation"""
    pass

class RunStatus:
    """Status of a valuation run"""
    pass

class PVBreakdown:
    """Present Value breakdown with lineage information"""
    pass
