name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  CONTAINER_NAME: valuation-backend
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  LOCATION: ${{ secrets.AZURE_LOCATION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
    
    - name: Deploy to Azure Container Instances
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az container create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CONTAINER_NAME }} \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest \
            --cpu 1 \
            --memory 2 \
            --ports 8000 \
            --environment-variables \
              OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              OPENAI_MODEL="gpt-4o-mini" \
              POC_ENABLE_IFRS="true" \
              POC_ENABLE_PARSE="true" \
              POC_ENABLE_EXPLAIN="true" \
            --ip-address Public \
            --dns-name-label valuation-backend-${{ github.run_number }}
